In [14]:
import numpy as np
import manifpy as m

# 1) 手动设置一个 SE2 位姿 x = (x, y, theta)
x = m.SE2(1.0, 2.0, 0.3)   # 平移 (1,2)，旋转 0.3 rad
print("x =", x)
print("x =", x.translation(), x.angle())

# 2) 手动设置一个 tangent 向量 tau = (dx, dy, dtheta)
tau = m.SE2Tangent(np.array([0.2, -0.1, 0.05]))
print("tau =", tau)

# 3) 加法：x ⊕ tau
y = x + tau
print("y = x + tau =", y)

# 4) 减法：y ⊖ x
tau_rec = y - x
print("tau_rec = y - x =", tau_rec.coeffs())

# 5) 检查误差
print("tau_rec - tau =", tau_rec.coeffs() - tau.coeffs())


x =        1        2 0.955336  0.29552
x = [1. 2.] 0.3
tau =  0.2 -0.1 0.05
y = x + tau =  1.22144   1.9691 0.939373 0.342898
tau_rec = y - x = [ 0.2  -0.1   0.05]
tau_rec - tau = [-1.38777878e-16 -2.49800181e-16  2.77555756e-17]


In [23]:
print(tau.rjac())

[[ 0.99958339  0.02499479  0.05165604]
 [-0.02499479  0.99958339  0.09914594]
 [ 0.          0.          1.        ]]


In [38]:
np.array([[1,2,3],[2,3,4],[4,5,6]])@tau.coeffs()

array([0.15, 0.3 , 0.6 ])